Added abilty to customize some components shape
KTibow/m3-svelte pull request #87
Opened 2023-11-26 17:37 UTC by hubertmalkowski

1. I've added css shape tokens from official docs [material design](https://m3.material.io/styles/shape/shape-scale-tokens#a830b8f8-f15b-4be9-8b2e-839f78481cf2)
2. Components with shape customization variable: 
    - Button
    - ButtonLink
    - FAB
    - SegmentedButton
    - BottomSheet
    - Card
    - CardClickable
    - Dialog
    - Menu
    - Chip
    - TextField (each type)
    - DateField

2023-11-26 17:52 UTC, KTibow requested changes
- :root is global without :global
- review the changes you made and undo ones that are out of scope

2023-11-26 17:56 UTC, KTibow commented on src/lib/forms/Chip.svelte
> +    --m3-chip-shape: var(--m3-util-rounding-full);
this is not true

2023-11-26 17:58 UTC, hubertmalkowski commented on src/lib/forms/Chip.svelte
> +    --m3-chip-shape: var(--m3-util-rounding-full);
Yep, sorry my bad. Missed that one.

2023-11-26 18:25 UTC, KTibow commented
do you have plans to finish doing this for the rest of components or should i implement them

2023-11-26 18:41 UTC, KTibow commented
the snackbar is... complicated. it needs to accomplish the following things:
- allow the box-shadow to not get clipped
- approximate a border radius with 2 intermediate points
- be able to animate from one form to another

2023-11-26 21:02 UTC, hubertmalkowski commented
I guess that's all except snackbar

2023-11-26 22:34 UTC, KTibow commented on src/lib/forms/SliderTicks.svelte
> +    height: var(--m3-slider-track-shape);
surely you meant to change the border radius not height

2023-11-26 22:34 UTC, KTibow commented on src/lib/forms/Slider.svelte
> +    --m3-slider-track-shape: var(--m3-util-rounding-extra-small);
this and the ticks one should be full, not extra small

2023-11-29 00:11 UTC, KTibow commented
merging this but not releasing a new version. i'd like it if people tried it out on the website before this breaks anything.

2023-11-29 00:11 UTC, merged